#!/bin/python3

import math
import os
import random
import re
import sys
def plusMinus(arr,n):
    p=0
    ne=0
    z=0
    for i in range(n):
        if arr[i]>0:
            p+=1
        elif arr[i]<0:
            ne+=1
        else:
            z+=1
    print(float(p/n))
    print( float(ne/n))
    print(float(z/n))
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr,n)
